services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: ratemy-postgres-simple
    restart: unless-stopped
    environment:
      POSTGRES_DB: ratemy_db
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_simple_data:/var/lib/postgresql/data
    networks:
      - ratemy-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U username -d ratemy_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Next.js Development Application
  app:
    build:
      context: .
      dockerfile: Dockerfile.simple
    container_name: ratemy-app-simple
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://username:password@postgres:5432/ratemy_db
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your-super-secret-jwt-secret-change-in-production
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - ratemy-network
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next

volumes:
  postgres_simple_data:
    driver: local

networks:
  ratemy-network:
    driver: bridge