services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: ratemy-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ratemy_db
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - ratemy-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U username -d ratemy_db"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  # Next.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ratemy-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://username:password@postgres:5432/ratemy_db
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your-super-secret-jwt-secret-change-in-production
      - LOG_LEVEL=info
      - HOST=0.0.0.0
      - PORT=3000
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - ratemy-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development version (alternative to production build)
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ratemy-app-dev
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://username:password@postgres:5432/ratemy_db
      - NEXTAUTH_URL=http://localhost:3001
      - NEXTAUTH_SECRET=your-super-secret-jwt-secret-change-in-production
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - ratemy-network
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    profiles:
      - dev

volumes:
  postgres_data:
    driver: local

networks:
  ratemy-network:
    driver: bridge